@php($registroDirecto = $registrarAccionDirecta ?? false)
@php($mostrarBoton = $mostrarBoton ?? true)
<style>
    .mp-escanear{display:flex;align-items:center;justify-content:center;gap:.5rem;width:100%;min-height:3rem;margin-top:1rem;border:0;border-radius:.625rem;background:var(--primary,#2563eb);color:#fff;font:inherit;font-weight:700;cursor:pointer}.mp-aviso{display:none;margin-top:.75rem;padding:.7rem .8rem;border:1px solid color-mix(in srgb,var(--app-danger,#b42318) 38%,var(--app-border,#d0d5dd));border-radius:.625rem;background:var(--app-danger-bg,#fef2f2);color:var(--app-danger,#b42318);font-size:.8125rem;line-height:1.4}.mp-overlay{display:none;position:fixed;inset:0;z-index:100;flex-direction:column;align-items:center;justify-content:center;padding:1rem;background:#101828}.mp-overlay.activo{display:flex}.mp-camara{position:relative;width:min(100%,25rem)}.mp-overlay video{width:100%;aspect-ratio:1;border-radius:.75rem;object-fit:cover}.mp-marco{position:absolute;inset:12%;border:2px solid #fff;border-radius:.625rem;box-shadow:0 0 0 999px rgb(0 0 0 / .35);pointer-events:none}.mp-estado{max-width:23rem;margin-top:.875rem;color:#fff;font-size:.875rem;text-align:center}.mp-overlay button{font:inherit;cursor:pointer}.mp-cancelar{margin-top:1rem;padding:.6rem 1rem;border:1px solid rgb(255 255 255 / .45);border-radius:.5rem;background:transparent;color:#fff}.mp-foto{display:inline-flex;align-items:center;justify-content:center;min-height:2.75rem;margin-top:.75rem;color:#fff;font-size:.8125rem;text-decoration:underline;cursor:pointer}.mp-foto input{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap}.mp-result{display:none;width:min(100%,25rem);padding:1.25rem;border:1px solid var(--line,var(--app-border,#d0d5dd));border-radius:.75rem;background:var(--surface,var(--app-surface,#fff));color:var(--ink,var(--app-text,#172033));text-align:center}.mp-result.activo{display:block}.mp-result-icono{width:2.5rem;height:2.5rem;margin:0 auto .625rem;color:var(--app-success,#15803d)}.mp-result h2{margin:0;font-size:1.0625rem}.mp-result p{margin:.35rem 0 0;color:var(--muted,var(--app-muted,#475467));font-size:.875rem}.mp-result-botones{display:grid;grid-template-columns:1fr 1fr;gap:.625rem;margin-top:.85rem}.mp-result-botones button{min-height:2.75rem;border-radius:.5rem;font-weight:700}.mp-continuar{border:0;background:var(--primary,#2563eb);color:#fff}.mp-reintentar{border:1px solid var(--line,var(--app-border,#d0d5dd));background:var(--surface,var(--app-surface,#fff));color:var(--ink,var(--app-text,#344054)}.mp-result.error .mp-result-icono{color:var(--app-danger,#b42318)}
</style>

<div class="mp-escaner" data-qr-scanner data-directo="{{ $registroDirecto ? '1' : '0' }}" data-ruta-validacion="{{ route('marcacion.validar-qr') }}" data-ruta-qr="{{ $rutaQr ?? '/marcar?token=' }}">
<div class="mp-aviso" data-qr-aviso-permiso>No se pudo acceder a la cámara. Revisa el permiso de cámara e inténtalo nuevamente o usa una foto del QR.</div>
@if($mostrarBoton)<button type="button" class="mp-escanear" data-qr-iniciar><x-heroicon-o-qr-code style="width:1.25rem;height:1.25rem" />{{ $textoBoton ?? 'Escanear QR de la estación' }}</button>@endif
@if($registroDirecto)<form id="mp-form-registro" method="POST" action="{{ route('marcacion.store') }}" hidden>@csrf<input id="mp-token-registro" name="token"></form>@endif

<div class="mp-overlay" data-qr-overlay aria-live="polite">
    <div class="mp-camara" data-qr-vista><video data-qr-video playsinline muted></video><div class="mp-marco"></div></div>
    <div class="mp-estado" data-qr-estado>Apunta la cámara al QR actual de la estación</div>
    <label class="mp-foto" data-qr-foto>Usar foto del QR<input data-qr-archivo type="file" accept="image/*" capture="environment"></label>
    <button type="button" class="mp-cancelar" data-qr-cancelar>Cancelar</button>
    <section class="mp-result" data-qr-resultado><x-heroicon-s-check-circle class="mp-result-icono" data-qr-icono /><h2 data-qr-titulo>QR validado</h2><p data-qr-detalle></p><div class="mp-result-botones"><button type="button" class="mp-reintentar" data-qr-reintentar>Escanear nuevamente</button><button type="button" class="mp-continuar" data-qr-continuar>Continuar</button></div></section>
</div>
</div>

@vite('resources/js/qr-scanner.js')
