@php($registroDirecto = $registrarAccionDirecta ?? false)
@php($mostrarBoton = $mostrarBoton ?? true)
<style>
    .mp-escanear{display:flex;align-items:center;justify-content:center;gap:.5rem;width:100%;min-height:3rem;margin-top:1rem;border:0;border-radius:.625rem;background:var(--primary,#2563eb);color:#fff;font:inherit;font-weight:700;cursor:pointer}.mp-aviso{display:none;margin-top:.75rem;padding:.7rem .8rem;border:1px solid color-mix(in srgb,var(--app-danger,#b42318) 38%,var(--app-border,#d0d5dd));border-radius:.625rem;background:var(--app-danger-bg,#fef2f2);color:var(--app-danger,#b42318);font-size:.8125rem;line-height:1.4}.mp-overlay{display:none;position:fixed;inset:0;z-index:100;flex-direction:column;align-items:center;justify-content:center;padding:1rem;background:#101828}.mp-overlay.activo{display:flex}.mp-camara{position:relative;width:min(100%,25rem)}.mp-overlay video{width:100%;aspect-ratio:1;border-radius:.75rem;object-fit:cover}.mp-marco{position:absolute;inset:12%;border:2px solid #fff;border-radius:.625rem;box-shadow:0 0 0 999px rgb(0 0 0 / .35);pointer-events:none}.mp-estado{max-width:23rem;margin-top:.875rem;color:#fff;font-size:.875rem;text-align:center}.mp-overlay button{font:inherit;cursor:pointer}.mp-cancelar{margin-top:1rem;padding:.6rem 1rem;border:1px solid rgb(255 255 255 / .45);border-radius:.5rem;background:transparent;color:#fff}.mp-result{display:none;width:min(100%,25rem);padding:1.25rem;border:1px solid var(--line,var(--app-border,#d0d5dd));border-radius:.75rem;background:var(--surface,var(--app-surface,#fff));color:var(--ink,var(--app-text,#172033));text-align:center}.mp-result.activo{display:block}.mp-result-icono{width:2.5rem;height:2.5rem;margin:0 auto .625rem;color:var(--app-success,#15803d)}.mp-result h2{margin:0;font-size:1.0625rem}.mp-result p{margin:.35rem 0 0;color:var(--muted,var(--app-muted,#475467));font-size:.875rem}.mp-result-botones{display:grid;grid-template-columns:1fr 1fr;gap:.625rem;margin-top:.85rem}.mp-result-botones button{min-height:2.75rem;border-radius:.5rem;font-weight:700}.mp-continuar{border:0;background:var(--primary,#2563eb);color:#fff}.mp-reintentar{border:1px solid var(--line,var(--app-border,#d0d5dd));background:var(--surface,var(--app-surface,#fff));color:var(--ink,var(--app-text,#344054)}.mp-result.error .mp-result-icono{color:var(--app-danger,#b42318)}
</style>

<div class="mp-aviso" id="mp-aviso-sin-soporte">Tu navegador no permite usar la cámara en esta pantalla. Abre el enlace desde la cámara del celular.</div>
<div class="mp-aviso" id="mp-aviso-sin-permiso">No se pudo acceder a la cámara. Revisa el permiso de cámara e inténtalo nuevamente.</div>
@if($mostrarBoton)<button type="button" class="mp-escanear" id="mp-btn-escanear"><x-heroicon-o-qr-code style="width:1.25rem;height:1.25rem" />{{ $textoBoton ?? 'Escanear QR de la estación' }}</button>@endif
@if($registroDirecto)<form id="mp-form-registro" method="POST" action="{{ route('marcacion.store') }}" hidden>@csrf<input id="mp-token-registro" name="token"></form>@endif

<div class="mp-overlay" id="mp-overlay-camara" aria-live="polite">
    <div class="mp-camara" id="mp-vista-camara"><video id="mp-video-camara" playsinline muted></video><div class="mp-marco"></div></div>
    <div class="mp-estado" id="mp-estado-camara">Apunta la cámara al QR actual de la estación</div>
    <button type="button" class="mp-cancelar" id="mp-btn-cancelar">Cancelar</button>
    <section class="mp-result" id="mp-result-qr"><x-heroicon-s-check-circle class="mp-result-icono" id="mp-result-icono" /><h2 id="mp-result-titulo">QR validado</h2><p id="mp-result-estacion"></p><div class="mp-result-botones"><button type="button" class="mp-reintentar" id="mp-btn-reintentar">Escanear nuevamente</button><button type="button" class="mp-continuar" id="mp-btn-continuar">Continuar</button></div></section>
</div>

<script>
(() => {
    const directo=@js($registroDirecto), iniciarBoton=document.getElementById('mp-btn-escanear'), cancelar=document.getElementById('mp-btn-cancelar'), reintentar=document.getElementById('mp-btn-reintentar'), continuar=document.getElementById('mp-btn-continuar'), overlay=document.getElementById('mp-overlay-camara'), video=document.getElementById('mp-video-camara'), estado=document.getElementById('mp-estado-camara'), avisoSoporte=document.getElementById('mp-aviso-sin-soporte'), avisoPermiso=document.getElementById('mp-aviso-sin-permiso'), vista=document.getElementById('mp-vista-camara'), resultado=document.getElementById('mp-result-qr'), titulo=document.getElementById('mp-result-titulo'), estacion=document.getElementById('mp-result-estacion'), form=document.getElementById('mp-form-registro');
    const rutaValidacion=@js(route('marcacion.validar-qr')), rutaPermitida=new URL(@js($rutaQr ?? '/marcar?token='),window.location.origin);
    let stream=null,escaneando=false,procesando=false,destino=null,token=null;
    const detener=()=>{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}};
    const restaurar=()=>{resultado.classList.remove('activo','error');vista.style.display='block';estado.style.display='block';cancelar.style.display='inline-block';};
    const cerrar=()=>{escaneando=false;procesando=false;destino=null;token=null;detener();restaurar();overlay.classList.remove('activo');};
    const resultadoQr=(ok,mensaje,detalle='')=>{detener();escaneando=false;procesando=true;vista.style.display='none';estado.style.display='none';cancelar.style.display='none';resultado.classList.add('activo');resultado.classList.toggle('error',!ok);titulo.textContent=ok?'QR escaneado correctamente':'No se pudo validar el QR';estacion.textContent=ok?'':mensaje;continuar.style.display=ok?'inline-block':'none';};
    const leerDestino=valor=>{try{const leido=new URL(valor,window.location.origin);if(leido.origin!==window.location.origin||leido.pathname!==rutaPermitida.pathname)return null;const codigo=leido.searchParams.get('token');return codigo?{token:codigo,url:leido.toString()}:null;}catch(_){return null;}};
    const validar=async dato=>{if(!directo){destino=dato.url;token=dato.token;resultadoQr(true,'');return;}try{const respuesta=await fetch(rutaValidacion+'?token='+encodeURIComponent(dato.token),{headers:{Accept:'application/json'},credentials:'same-origin'}),cuerpo=await respuesta.json();if(!respuesta.ok||!cuerpo.confirmado){resultadoQr(false,cuerpo.mensaje||'El QR no se pudo validar.');return;}destino=dato.url;token=dato.token;resultadoQr(true,'');}catch(_){resultadoQr(false,'No se pudo validar el QR. Verifica tu conexión e inténtalo nuevamente.');}};
    const iniciar=async()=>{avisoSoporte.style.display='none';avisoPermiso.style.display='none';if(!('BarcodeDetector'in window)){avisoSoporte.style.display='block';return;}restaurar();procesando=false;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});}catch(_){avisoPermiso.style.display='block';return;}video.srcObject=stream;await video.play();overlay.classList.add('activo');const detector=new BarcodeDetector({formats:['qr_code']});escaneando=true;const ciclo=async()=>{if(!escaneando||procesando)return;try{const codigos=await detector.detect(video);if(codigos.length){const dato=leerDestino(codigos[0].rawValue||'');if(dato){procesando=true;estado.textContent='Validando QR…';await validar(dato);return;}estado.textContent='Este QR no se puede usar para marcar.';}}catch(_){}requestAnimationFrame(ciclo);};requestAnimationFrame(ciclo);};
    iniciarBoton?.addEventListener('click',iniciar);cancelar?.addEventListener('click',cerrar);reintentar?.addEventListener('click',iniciar);continuar?.addEventListener('click',()=>{if(directo&&form&&token){document.getElementById('mp-token-registro').value=token;form.submit();return;}if(destino)window.location.assign(destino);});window.addEventListener('pagehide',detener);
})();
</script>
