<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Confirmar marcación — {{ $apariencia->nombre() }}</title><link rel="icon" href="{{ $apariencia->iconoUrl() }}"><x-pwa-head /><x-public-theme />
    <style>
        :root{--primary:{{ $apariencia->colorPrimario() }};--page:var(--app-page);--surface:var(--app-surface);--soft:var(--app-subtle);--ink:var(--app-text);--muted:var(--app-muted);--line:var(--app-border)}*{box-sizing:border-box}body{min-height:100dvh;margin:0;display:grid;place-items:center;padding:1rem;background:var(--page);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.card{width:min(100%,30rem);padding:1.25rem;background:var(--surface);border:1px solid var(--line);border-radius:.875rem}.brand{display:flex;align-items:center;justify-content:space-between;padding-bottom:1rem;margin-bottom:1rem;border-bottom:1px solid var(--line)}.brand img{height:2.25rem;max-width:8rem;object-fit:contain}.brand span{color:var(--muted);font-size:.75rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase}h1{margin:0;font-size:1.25rem}.sub{margin:.3rem 0 1rem;color:var(--muted);font-size:.875rem}.lectura{display:flex;gap:.65rem;padding:.8rem .875rem;border:1px solid color-mix(in srgb,var(--app-success) 45%,var(--line));border-radius:.75rem;background:var(--app-success-bg);color:var(--app-success);font-size:.875rem;line-height:1.4}.lectura svg{width:1.35rem;height:1.35rem;flex:0 0 auto}.lectura strong{display:block}.lectura span{display:block;margin-top:.1rem}.errores{margin-top:.85rem;padding:.75rem;border:1px solid color-mix(in srgb,var(--app-danger) 40%,var(--line));border-radius:.625rem;background:var(--app-danger-bg);color:var(--app-danger);font-size:.8125rem}.confirmar{width:100%;min-height:3rem;margin-top:1rem;border:0;border-radius:.625rem;background:var(--primary);color:#fff;font:inherit;font-weight:700;cursor:pointer}.links{display:flex;justify-content:space-between;margin-top:1rem}.links a,.links button{display:inline-flex;align-items:center;gap:.35rem;min-height:2.5rem;border:0;background:none;padding:0;color:var(--muted);font:inherit;font-size:.8125rem;text-decoration:none;cursor:pointer}@media(max-width:640px){body{display:block;padding:0}.card{min-height:100dvh;width:100%;padding:1.25rem 1rem calc(1.25rem + env(safe-area-inset-bottom));border:0;border-radius:0}}
    </style>
</head>
<body>
<main class="card"><header class="brand"><img src="{{ $apariencia->logoUrl() }}" alt="{{ $apariencia->nombre() }}"><span>Marcación</span></header><h1>QR escaneado correctamente</h1><p class="sub">{{ $colaborador->nombre_completo }}</p><div class="lectura"><x-heroicon-s-check-circle /><div><strong>Listo para registrar</strong><span>Confirma para que el sistema identifique la marcación correspondiente.</span></div></div>@if($errors->any())<div class="errores">@foreach($errors->all() as $error){{ $error }}<br>@endforeach</div>@endif<form method="POST" action="{{ route('marcacion.store') }}">@csrf<input type="hidden" name="token" value="{{ $token }}"><button class="confirmar" type="submit">Registrar marcación</button></form><div class="links"><a href="{{ route('marcacion.show') }}"><x-heroicon-o-camera style="width:1rem;height:1rem" />Escanear otro QR</a><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit"><x-heroicon-o-arrow-left-on-rectangle style="width:1rem;height:1rem" />Cerrar sesión</button></form></div></main>
</body>
</html>
