<?php

use App\Models\Sucursal;
use App\Models\Turno;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Repara instalaciones que registraron las migraciones iniciales sin
     * materializar la tabla. No usa hasTable() antes de crearla: en dichos
     * entornos el inspector de esquema puede devolver un dato obsoleto.
     */
    public function up(): void
    {
        if (DB::connection()->getDriverName() === 'pgsql') {
            // PostgreSQL evalúa IF NOT EXISTS en el propio motor, sin depender
            // del inspector de esquemas de la conexión de PHP.
            DB::statement(<<<'SQL'
                CREATE TABLE IF NOT EXISTS turnos_operativos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    turno_id BIGINT NOT NULL REFERENCES turnos(id) ON DELETE RESTRICT,
                    sucursal_id BIGINT NOT NULL REFERENCES sucursales(id) ON DELETE CASCADE,
                    punto_venta_id BIGINT NULL REFERENCES puntos_venta(id) ON DELETE CASCADE,
                    prioridad SMALLINT NOT NULL DEFAULT 100,
                    activo BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL
                )
                SQL);
            DB::statement('CREATE INDEX IF NOT EXISTS turno_operativo_estacion_activo ON turnos_operativos (sucursal_id, punto_venta_id, activo)');
        } elseif (! Schema::hasTable('turnos_operativos')) {
            Schema::create('turnos_operativos', function ($table): void {
                $table->id();
                $table->foreignId('turno_id')->constrained('turnos')->restrictOnDelete();
                $table->foreignId('sucursal_id')->constrained('sucursales')->cascadeOnDelete();
                $table->foreignId('punto_venta_id')->nullable()->constrained('puntos_venta')->cascadeOnDelete();
                $table->unsignedSmallInteger('prioridad')->default(100);
                $table->boolean('activo')->default(true);
                $table->timestamps();
                $table->index(['sucursal_id', 'punto_venta_id', 'activo'], 'turno_operativo_estacion_activo');
            });
        }

        $turnos = Turno::query()
            ->whereIn('nombre', ['Apertura', 'Cierre'])
            ->pluck('id');

        Sucursal::query()
            ->where('tipo', 'tienda')
            ->where('activo', true)
            ->each(function (Sucursal $sucursal) use ($turnos): void {
                foreach ($turnos as $turnoId) {
                    DB::table('turnos_operativos')->insert([
                        'turno_id' => $turnoId,
                        'sucursal_id' => $sucursal->id,
                        'punto_venta_id' => null,
                        'prioridad' => 100,
                        'activo' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            });
    }

    public function down(): void
    {
        Schema::dropIfExists('turnos_operativos');
    }
};
